# Generated by Django 6.0.5 on 2026-05-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('user_id', models.IntegerField()),
                ('merchant_id', models.IntegerField()),
                ('amount', models.FloatField()),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Electronics', 'Electronics'), ('Health', 'Health'), ('Entertainment', 'Entertainment'), ('Retail', 'Retail'), ('Transport', 'Transport'), ('Education', 'Education'), ('Services', 'Services'), ('Other', 'Other')], max_length=20)),
                ('country_code', models.CharField(choices=[('MX', 'MX'), ('CO', 'CO'), ('BR', 'BR'), ('AR', 'AR'), ('CL', 'CL'), ('PE', 'PE'), ('EC', 'EC'), ('VE', 'VE'), ('BO', 'BO'), ('PY', 'PY'), ('UY', 'UY'), ('CR', 'CR'), ('GT', 'GT'), ('PA', 'PA'), ('DO', 'DO')], max_length=2)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('failed', 'failed'), ('pending', 'pending')], max_length=20)),
            ],
            options={
                'db_table': 'transactions',
                'indexes': [models.Index(fields=['user_id', '-timestamp'], name='idx_txns_user_timestamp'), models.Index(fields=['country_code', 'user_id'], name='idx_txns_country_user')],
            },
        ),
    ]
